# build environment
FROM node:8.16.0-alpine as build
COPY ./infra/dumb-init /infra/dumb-init
COPY ./my-koa /my-koa
RUN cd /my-koa && \
    npm i --save koa \
        koa-router \
        koa-sse-stream \
        mongodb \
        ioredis \
        koa-generic-session \
        koa-redis

WORKDIR my-koa

EXPOSE 8000
ENTRYPOINT ["/infra/dumb-init", "--"]
CMD ["node", "app.js"]